# Generated by Django 3.2.14 on 2022-07-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_intro_url',
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
